### PR TITLE
General markdown tweaks

### PR DESCRIPTION
**Pull request by tyler36**
## Overview

This PR fixes some common markdown "problems"

- Top-level heading
- Indentation

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
Maybe I'm wrong but seems like the header should go after the badge.

**Comment by tyler36** [comment]
Note: the table of contents was auto-generated via the [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) VSCode extension.  The `<!-- omit in toc -->` help the extension determine what to include.

This extension also auto-update the TOC in real time and is awesome if you use VSCode and markdown.

**Comment by rfay** [comment]
What TOC?

**Comment by tyler36** [comment]
Sorry, wrong thread. :(

**Review by rfay — APPROVED** [review]
Sorry lost track.

**Pull request merged**
